### PR TITLE
HL-360

### PR DESCRIPTION
**Pull request by Mitchell139**
https://dltx.atlassian.net/browse/HL-360?atlOrigin=eyJpIjoiZDZjZGJhZjE5ODUwNDcwZTk1NzE4ODQ1YjAzNWEwODgiLCJwIjoiaiJ9 

Fix/update/improve various parts of contract readme

### CODE REVIEW

**Review by OptimusOpus — DISMISSED** [review]
LGTM

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Great start. Let’s not say TAB odds as that’s just a temporary method

**Review by Choxel — APPROVED** [review]
Nice

**Comment by TomDodson** [comment]
Nice

**Review by TomDodson — APPROVED** [review]

**Review by bitcoinbrisbane — APPROVED** [review]

**Pull request merged**
