### PR TITLE
HL-414

### PR DESCRIPTION
**Pull request by OptimusOpus**
[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-414)

### CODE REVIEW

**Review by bazmatic — APPROVED** [review]

**Comment by bazmatic** [comment]
Weird, SonarCloud is complaining about test code you didn't add in this PR...

**Review by bitcoinbrisbane — COMMENTED** [review]
How do we knows who's bet is who's?

**Review by bitcoinbrisbane — COMMENTED** [review]
Is this so we can transfer bets and NFT owner is the owner?

**Comment by OptimusOpus** [comment]
> Weird, SonarCloud is complaining about test code you didn't add in this PR...

Yeah I have seen sonarclound be like that with the unti tests

**Review by bitcoinbrisbane — APPROVED** [review]

**Pull request merged**
